import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

part 'offline_action_queue.g.dart';

/// Tipos de acciones que pueden ser encoladas
@HiveType(typeId: 11)
enum GameActionType {
  @HiveField(0)
  answerSubmission,    // Envio de respuesta
  @HiveField(1)
  battleComplete,      // Batalla completada
  @HiveField(2)
  xpGain,             // Ganancia de XP
  @HiveField(3)
  goldTransaction,    // Transaccion de oro
  @HiveField(4)
  streakUpdate,       // Actualizacion de racha
  @HiveField(5)
  achievementUnlock,  // Desbloqueo de logro
  @HiveField(6)
  heartUse,           // Uso de corazon
  @HiveField(7)
  nodeComplete,       // Completar nodo
  @HiveField(8)
  nodeUnlock,         // Desbloquear nodo
  @HiveField(9)
  purchaseItem,       // Compra en tienda
}

/// Accion pendiente de sincronizar
@HiveType(typeId: 10)
class PendingAction extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final GameActionType type;

  @HiveField(2)
  final Map<String, dynamic> payload;

  @HiveField(3)
  final DateTime timestamp;

  @HiveField(4)
  int retryCount;

  PendingAction({
    required this.id,
    required this.type,
    required this.payload,
    required this.timestamp,
    this.retryCount = 0,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type.name,
    'payload': payload,
    'timestamp': timestamp.toIso8601String(),
    'retry_count': retryCount,
  };
}

/// Cola de Acciones Offline
///
/// Permite que el juego funcione sin conexion y sincroniza
/// cuando vuelve a estar online.
///
/// PRINCIPIO: 100% offline-first para Colombia (buses, metro, zonas rurales)
class OfflineActionQueue extends ChangeNotifier {
  late Box<PendingAction> _queue;
  bool _isInitialized = false;
  bool _isSyncing = false;
  
  // Using singleton pattern for Connectivity if needed, or just new instance
  final Connectivity _connectivity = Connectivity();

  /// Callback para enviar acciones al servidor
  Future<bool> Function(PendingAction action)? onSendAction;

  /// Inicializa la cola
  Future<void> initialize() async {
    if (_isInitialized) return;

    // Registrar adapter de Hive
    // Note: PendingActionAdapter is generated by build_runner
    if (!Hive.isAdapterRegistered(10)) {
      Hive.registerAdapter(PendingActionAdapter());
    }
    if (!Hive.isAdapterRegistered(11)) {
        Hive.registerAdapter(GameActionTypeAdapter());
    }

    _queue = await Hive.openBox<PendingAction>('offline_queue');
    _isInitialized = true;

    // Escuchar cambios de conectividad
    _connectivity.onConnectivityChanged.listen((result) {
      // result can be a list in newer versions, checking accordingly
      // Assuming older version based on code provided, but if list it breaks. 
      // Connectivity plus v6 returns List<ConnectivityResult> in onConnectivityChanged?
      // No, stream is Stream<List<ConnectivityResult>> in v6.
      // Let's handle both or assume the code provided is correct for the installed version.
      // Pubspec said ^6.0.0. In 6.0.0 it returns List<ConnectivityResult>.
      // The provided code: `listen((result) { if (result != ConnectivityResult.none)` suggests older version style.
      // I will adapt it to support list if needed or just `checkConnectivity` which also returns list.
      // Actually, let's just stick to checking if it contains mobile or wifi.
      
      // Since I cannot easily change the logic without risking compilation errors if I guess wrong about the exact API match,
      // I will assume the provided code might need slight adjustment for v6.
      // In v6: Stream<List<ConnectivityResult>> onConnectivityChanged
      // Implementation below tries to be safe.
      
      syncPendingActions();
    });

    // Intentar sync inicial
    syncPendingActions();
  }

  /// Cantidad de acciones pendientes
  int get pendingCount => _queue.length;

  /// Verifica si esta online
  Future<bool> get isOnline async {
    final result = await _connectivity.checkConnectivity();
    // result is List<ConnectivityResult> in v6
    return result.contains(ConnectivityResult.mobile) || 
           result.contains(ConnectivityResult.wifi) ||
           result.contains(ConnectivityResult.ethernet);
  }

  /// Encola una accion para sincronizar
  ///
  /// Si esta online, intenta enviar inmediatamente.
  /// Si esta offline, guarda para enviar despues.
  Future<void> enqueue(GameActionType type, Map<String, dynamic> payload) async {
    final action = PendingAction(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      type: type,
      payload: payload,
      timestamp: DateTime.now(),
    );

    if (await isOnline && onSendAction != null) {
      // Intentar enviar inmediatamente
      final success = await onSendAction!(action);
      if (success) {
        debugPrint('OfflineQueue: Action sent immediately');
        return;
      }
    }

    // Guardar para despues
    await _queue.put(action.id, action);
    debugPrint('OfflineQueue: Action queued (${_queue.length} pending)');
    notifyListeners();
  }

  /// Encola un envio de respuesta
  Future<void> enqueueAnswerSubmission({
    required String encounterId,
    required String questionId,
    required String answerId,
    required int timeSpentSeconds,
  }) async {
    await enqueue(GameActionType.answerSubmission, {
      'encounter_id': encounterId,
      'question_id': questionId,
      'answer_id': answerId,
      'time_spent_seconds': timeSpentSeconds,
    });
  }

  /// Encola una batalla completada
  Future<void> enqueueBattleComplete({
    required String runId,
    required bool victory,
    required int xpEarned,
    required int goldEarned,
    required int starsEarned,
  }) async {
    await enqueue(GameActionType.battleComplete, {
      'run_id': runId,
      'victory': victory,
      'xp_earned': xpEarned,
      'gold_earned': goldEarned,
      'stars_earned': starsEarned,
    });
  }

  /// Encola uso de corazon
  Future<void> enqueueHeartUse() async {
    await enqueue(GameActionType.heartUse, {
      'used_at': DateTime.now().toIso8601String(),
    });
  }

  /// Encola extension de racha
  Future<void> enqueueStreakExtend({required int xpEarned}) async {
    await enqueue(GameActionType.streakUpdate, {
      'xp_earned': xpEarned,
      'activity_date': DateTime.now().toIso8601String().split('T')[0],
    });
  }

  /// Encola completar nodo
  Future<void> enqueueNodeComplete({
    required String nodeId,
    required String kingdomId,
    required double accuracy,
    List<String> questionsAnswered = const [],
  }) async {
    await enqueue(GameActionType.nodeComplete, {
      'node_id': nodeId,
      'kingdom_id': kingdomId,
      'accuracy': accuracy,
      'questions_answered': questionsAnswered,
    });
  }

  /// Encola desbloqueo de nodo
  Future<void> enqueueNodeUnlock({
    required String nodeId,
    required String kingdomId,
  }) async {
    await enqueue(GameActionType.nodeUnlock, {
      'node_id': nodeId,
      'kingdom_id': kingdomId,
    });
  }

  /// Encola compra de item
  Future<void> enqueuePurchase({
    required String itemId,
    required int quantity,
    required String currency,
  }) async {
    await enqueue(GameActionType.purchaseItem, {
      'item_id': itemId,
      'quantity': quantity,
      'currency': currency,
    });
  }

  /// Sincroniza todas las acciones pendientes
  Future<void> syncPendingActions() async {
    if (_isSyncing || onSendAction == null) return;
    if (!await isOnline) return;
    if (_queue.isEmpty) return;

    _isSyncing = true;
    debugPrint('OfflineQueue: Starting sync of ${_queue.length} actions');

    final actions = _queue.values.toList();

    for (final action in actions) {
      try {
        final success = await onSendAction!(action);

        if (success) {
          await _queue.delete(action.id);
          debugPrint('OfflineQueue: Synced action ${action.id}');
        } else {
          action.retryCount++;
          if (action.retryCount >= 3) {
            // Descartar despues de 3 intentos fallidos
            await _queue.delete(action.id);
            debugPrint('OfflineQueue: Discarded action after 3 retries');
          } else {
             action.save(); // Save retry count
          }
        }
      } catch (e) {
        debugPrint('OfflineQueue: Sync error: $e');
        action.retryCount++;
        action.save();
      }
    }

    _isSyncing = false;
    notifyListeners();
    debugPrint('OfflineQueue: Sync complete (${_queue.length} remaining)');
  }

  /// Limpia la cola (usar con cuidado)
  Future<void> clearQueue() async {
    await _queue.clear();
    notifyListeners();
  }
}
